# Generated by Django 5.1.7 on 2025-03-23 17:43

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE file_info
                ADD FULLTEXT INDEX fileinfo_fulltext_idx (name, preview);
            """,
            reverse_sql="""
                ALTER TABLE file_info
                DROP INDEX fileinfo_fulltext_idx;
            """
        )
    ]
