# Generated by Django 5.1.7 on 2025-03-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("be_django", "0001_add_fulltext_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=1024)),
                ("type", models.CharField(default="unknown", max_length=255)),
                ("size", models.BigIntegerField(default=0)),
                ("last_modified", models.DateTimeField()),
                ("creation_time", models.DateTimeField()),
                ("preview", models.TextField(blank=True)),
            ],
            options={
                "db_table": "file_info",
            },
        ),
    ]
